### ISSUE TITLE
Extension fails to load (TypeError)

### ISSUE THREAD

**Issue by PeterN** [fthx/simple-task-bar#3]
Hi,

I'm using Gnome Shell 3.30 (Debian 10). Since 50ef969de, I get the following error preventing this extension from working:

TypeError: activities_indicator.hide is not a function

**Comment by fthx** [comment]
What I would try without searching fine tricks in GS documentation... :
change
`activities_indicator.hide()`
to
`activities_indicator.container.hide()`
and do the similar action to the show in disable function.

**Comment by fthx** [comment]
https://extensions.gnome.org/review/15102
You can download the zip from the above link, Files section. I think you know that.

It still works with GS 3.36, so it's ok for this part ; it should work now for GS 3.30.
Tell me if it does work for you. If it does, the version 21 of the extension will solve this issue.

**Comment by fthx** [comment]
https://github.com/fthx/simple-task-bar/commit/d6b78d9f52987ac49c3550eec77b2c298aba1fc9

**Comment by PeterN** [comment]
This change works for me, thanks for the quick fix!

**Comment by fthx** [comment]
You're welcome. There are some change in GS 3.36 that make me miss some bugs and I don't have the time to test all the GS versions. Thanks for you quick feedback. :-) 
If you have some time, please give your opinion here : 
https://github.com/fthx/simple-task-bar/issues/2
